/**
 * SUPABASE SERVICE MODULE - Toko Super Komputer
 * Modul terpisah untuk menangani seluruh koneksi dan operasi CRUD Database PostgreSQL Supabase
 * SPK 10 Kriteria (C1 - C10): ROC & TOPSIS
 */

const SUPABASE_CONFIG = {
  URL: "https://jaizwaoqbqykvyvdxjyj.supabase.co",
  ANON_KEY: "sb_publishable_l9p5lowmhr4nK9-JD7B93w_tfhrTtRB"
};

// Inisialisasi Supabase Client
let supabaseClient = null;
try {
  if (typeof supabase !== 'undefined' && supabase.createClient) {
    supabaseClient = supabase.createClient(SUPABASE_CONFIG.URL, SUPABASE_CONFIG.ANON_KEY);
  }
} catch (err) {
  console.error("Gagal menginisialisasi Supabase Client:", err);
}

const SupabaseService = {
  client: supabaseClient,

  // Script SQL DDL untuk Setup / Migrasi Database 10 Kriteria
  SQL_SCHEMA: `-- ============================================================================
-- SQL DDL & MIGRASI DATABASE SPK 10 KRITERIA (C1 - C10) - TOKO SUPER KOMPUTER
-- Jalankan script ini di SQL Editor Supabase Dashboard:
-- ============================================================================

-- 1. TABEL MASTER KRITERIA (10 Kriteria)
CREATE TABLE IF NOT EXISTS public.kriteria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode VARCHAR(10) UNIQUE NOT NULL,
    nama VARCHAR(100) NOT NULL,
    tipe VARCHAR(10) CHECK (tipe IN ('Benefit', 'Cost')) NOT NULL,
    satuan VARCHAR(50) NOT NULL,
    keterangan TEXT,
    default_rank INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABEL ALTERNATIF LAPTOP (Lengkap 10 Kriteria C1 - C10)
CREATE TABLE IF NOT EXISTS public.laptops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(150) NOT NULL,
    merek VARCHAR(50) NOT NULL,
    status VARCHAR(20) CHECK (status IN ('ready', 'indent')) NOT NULL DEFAULT 'ready',
    kategori_penggunaan VARCHAR(50) DEFAULT 'Umum',
    harga NUMERIC(15, 2) NOT NULL,
    cpu_score NUMERIC(6, 2) NOT NULL,
    ram_gb INT NOT NULL,
    ssd_gb INT NOT NULL,
    gpu_score NUMERIC(6, 2) NOT NULL,
    baterai_wh NUMERIC(6, 2) NOT NULL,
    berat_kg NUMERIC(4, 2) NOT NULL,
    layar_score NUMERIC(6, 2) NOT NULL,
    garansi_score NUMERIC(4, 2) NOT NULL DEFAULT 1,
    upgrade_score NUMERIC(4, 2) NOT NULL DEFAULT 1,
    spesifikasi_ringkas TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. JIKA TABEL SUDAH ADA SEBELUMNYA, TAMBAHKAN KOLOM C9 & C10 OTOMATIS:
ALTER TABLE public.laptops ADD COLUMN IF NOT EXISTS garansi_score NUMERIC(4, 2) NOT NULL DEFAULT 1;
ALTER TABLE public.laptops ADD COLUMN IF NOT EXISTS upgrade_score NUMERIC(4, 2) NOT NULL DEFAULT 1;

-- 4. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.kriteria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.laptops ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'kriteria' AND policyname = 'Public Read Kriteria') THEN
        CREATE POLICY "Public Read Kriteria" ON public.kriteria FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'laptops' AND policyname = 'Public Read Laptops') THEN
        CREATE POLICY "Public Read Laptops" ON public.laptops FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'laptops' AND policyname = 'Public Insert Laptops') THEN
        CREATE POLICY "Public Insert Laptops" ON public.laptops FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'laptops' AND policyname = 'Public Update Laptops') THEN
        CREATE POLICY "Public Update Laptops" ON public.laptops FOR UPDATE USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'laptops' AND policyname = 'Public Delete Laptops') THEN
        CREATE POLICY "Public Delete Laptops" ON public.laptops FOR DELETE USING (true);
    END IF;
END $$;

-- 5. SEED 10 KRITERIA STANDAR KE DATABASE
INSERT INTO public.kriteria (kode, nama, tipe, satuan, keterangan, default_rank) VALUES
('C1', 'Harga Beli', 'Cost', 'Rupiah', 'Budget harga pembelian toko (makin hemat makin prioritas)', 1),
('C2', 'Processor (CPU)', 'Benefit', 'Skor 0-100', 'Performa komputasi inti prosesor', 2),
('C3', 'Kapasitas RAM', 'Benefit', 'GB', 'Memori multitasking dan rendering', 3),
('C4', 'Kapasitas SSD', 'Benefit', 'GB', 'Kapasitas penyimpanan sistem dan data', 4),
('C5', 'Kartu Grafis (GPU)', 'Benefit', 'Skor 0-100', 'Performa visual, gaming, dan 3D rendering', 5),
('C6', 'Daya Tahan Baterai', 'Benefit', 'Wh', 'Kapasitas baterai (Wh) durasi operasional', 6),
('C7', 'Portabilitas (Berat)', 'Cost', 'Kg', 'Bobot fisik laptop (makin ringan makin baik)', 7),
('C8', 'Kualitas Layar', 'Benefit', 'Skor 0-100', 'Skor kualitas panel, warna, dan refresh rate', 8),
('C9', 'Masa & Layanan Garansi', 'Benefit', 'Skala 1-5', 'Durasi garansi resmi dan proteksi ADP (1-5)', 9),
('C10', 'Kemampuan Upgrade', 'Benefit', 'Skala 1-5', 'Fleksibilitas upgrade RAM & storage SSD (1-5)', 10)
ON CONFLICT (kode) DO UPDATE SET 
    nama = EXCLUDED.nama,
    tipe = EXCLUDED.tipe,
    satuan = EXCLUDED.satuan,
    keterangan = EXCLUDED.keterangan,
    default_rank = EXCLUDED.default_rank;`,

  /**
   * Cek apakah error disebabkan karena tabel belum dibuat di database
   */
  isTableMissingError(error) {
    if (!error) return false;
    const msg = (error.message || '').toLowerCase();
    const code = error.code || '';
    return (
      code === 'PGRST205' ||
      msg.includes('could not find the table') ||
      msg.includes('schema cache') ||
      msg.includes('relation') ||
      msg.includes('does not exist')
    );
  },

  /**
   * Ambil seluruh data laptop dari Supabase
   * @returns {Promise<{data: Array, error: any, isTableMissing: boolean}>}
   */
  async getLaptops() {
    if (!supabaseClient) {
      return { data: null, error: new Error('Supabase client belum terpasang'), isTableMissing: false };
    }

    try {
      const { data, error } = await supabaseClient
        .from('laptops')
        .select('*')
        .order('id', { ascending: false });

      if (error) {
        return {
          data: null,
          error,
          isTableMissing: this.isTableMissingError(error)
        };
      }

      return { data: data || [], error: null, isTableMissing: false };
    } catch (err) {
      return {
        data: null,
        error: err,
        isTableMissing: this.isTableMissingError(err)
      };
    }
  },

  /**
   * Tambahkan laptop baru ke Supabase
   * @param {Object} laptopData 
   * @returns {Promise<{data: any, error: any, isTableMissing: boolean}>}
   */
  async insertLaptop(laptopData) {
    if (!supabaseClient) {
      return { data: null, error: new Error('Supabase client belum terpasang'), isTableMissing: false };
    }

    try {
      const { data, error } = await supabaseClient
        .from('laptops')
        .insert([laptopData])
        .select();

      if (error) {
        return { data: null, error, isTableMissing: this.isTableMissingError(error) };
      }
      return { data, error: null, isTableMissing: false };
    } catch (err) {
      return { data: null, error: err, isTableMissing: this.isTableMissingError(err) };
    }
  },

  /**
   * Perbarui data laptop di Supabase berdasarkan ID
   * @param {number|string} id 
   * @param {Object} laptopData 
   * @returns {Promise<{data: any, error: any, isTableMissing: boolean}>}
   */
  async updateLaptop(id, laptopData) {
    if (!supabaseClient) {
      return { data: null, error: new Error('Supabase client belum terpasang'), isTableMissing: false };
    }

    try {
      const { data, error } = await supabaseClient
        .from('laptops')
        .update(laptopData)
        .eq('id', id)
        .select();

      if (error) {
        return { data: null, error, isTableMissing: this.isTableMissingError(error) };
      }
      return { data, error: null, isTableMissing: false };
    } catch (err) {
      return { data: null, error: err, isTableMissing: this.isTableMissingError(err) };
    }
  },

  /**
   * Hapus data laptop dari Supabase berdasarkan ID
   * @param {number|string} id 
   * @returns {Promise<{error: any, isTableMissing: boolean}>}
   */
  async deleteLaptop(id) {
    if (!supabaseClient) {
      return { error: new Error('Supabase client belum terpasang'), isTableMissing: false };
    }

    try {
      const { error } = await supabaseClient
        .from('laptops')
        .delete()
        .eq('id', id);

      if (error) {
        return { error, isTableMissing: this.isTableMissingError(error) };
      }
      return { error: null, isTableMissing: false };
    } catch (err) {
      return { error: err, isTableMissing: this.isTableMissingError(err) };
    }
  },

  /**
   * Hapus banyak laptop sekaligus (Bulk Delete) berdasarkan daftar ID
   * @param {Array<number|string>} ids 
   * @returns {Promise<{error: any, isTableMissing: boolean}>}
   */
  async deleteMultipleLaptops(ids) {
    if (!supabaseClient) {
      return { error: new Error('Supabase client belum terpasang'), isTableMissing: false };
    }

    try {
      const { error } = await supabaseClient
        .from('laptops')
        .delete()
        .in('id', ids);

      if (error) {
        return { error, isTableMissing: this.isTableMissingError(error) };
      }
      return { error: null, isTableMissing: false };
    } catch (err) {
      return { error: err, isTableMissing: this.isTableMissingError(err) };
    }
  },

  /**
   * Bulk insert data contoh / seed demo
   * @param {Array} laptopsArray 
   * @returns {Promise<{data: any, error: any, isTableMissing: boolean}>}
   */
  async seedLaptops(laptopsArray) {
    if (!supabaseClient) {
      return { data: null, error: new Error('Supabase client belum terpasang'), isTableMissing: false };
    }

    try {
      const { data, error } = await supabaseClient
        .from('laptops')
        .insert(laptopsArray)
        .select();

      if (error) {
        return { data: null, error, isTableMissing: this.isTableMissingError(error) };
      }
      return { data, error: null, isTableMissing: false };
    } catch (err) {
      return { data: null, error: err, isTableMissing: this.isTableMissingError(err) };
    }
  }
};

// Export untuk browser window
window.SupabaseService = SupabaseService;
